# Generated by Django 4.2.7 on 2025-10-25 17:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Training title or name', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the training')),
                ('training_type', models.CharField(choices=[('CONFERENCE', 'Conference'), ('COURSE', 'Course'), ('CERTIFICATION', 'Certification'), ('WORKSHOP', 'Workshop')], help_text='Type of training being requested', max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, help_text='Estimated cost in the specified currency', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR)', max_length=3)),
                ('start_date', models.DateField(help_text='Training start date')),
                ('end_date', models.DateField(help_text='Training end date')),
                ('justification', models.TextField(help_text='Business justification for the training')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Current status of the request', max_length=20)),
                ('review_comments', models.TextField(blank=True, help_text='Comments from the reviewer')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the training was completed', null=True)),
                ('completion_notes', models.TextField(blank=True, help_text='Notes about the training completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(help_text='User who submitted the training request', on_delete=django.db.models.deletion.CASCADE, related_name='training_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, help_text='Leadership member who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Request',
                'verbose_name_plural': 'Training Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
