# Generated by Django 4.2.7 on 2025-10-26 07:33

import django.core.validators
from django.db import migrations, models
import training_requests.models


class Migration(migrations.Migration):

    dependencies = [
        ('training_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='supporting_documents',
            field=models.FileField(blank=True, help_text='Optional supporting documents (PDF, DOC, DOCX, TXT, up to 10MB)', null=True, upload_to='training_requests/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt'], message='Only PDF, DOC, DOCX, and TXT files are allowed.'), training_requests.models.validate_file_size]),
        ),
    ]
