# Generated by Django 4.2.7 on 2025-10-25 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REQUEST_SUBMITTED', 'Request Submitted'), ('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_DENIED', 'Request Denied'), ('REQUEST_COMPLETED', 'Request Completed')], help_text='Type of notification sent', max_length=20)),
                ('recipients', models.JSONField(help_text='List of recipient emails or user IDs')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False, help_text='Whether the notification was sent successfully')),
                ('error_message', models.TextField(blank=True, help_text='Error message if notification failed')),
                ('webhook_url', models.URLField(blank=True, help_text='Microsoft Teams webhook URL used')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts made')),
                ('request', models.ForeignKey(help_text='Training request this notification is about', on_delete=django.db.models.deletion.CASCADE, to='training_requests.trainingrequest')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
